export enum Ancestry {
    CLANK = 1,
    DRAKONA = 2,
    DWARF = 3,
    ELF = 4,
    FAERIE = 5,
    FAUN = 6,
    FIRBOLG = 7,
    FUNGRIL = 8,
    GALAPA = 9,
    GIANT = 10,
    GOBLIN = 11,
    HALFLING = 12,
    HUMAN = 13,
    INFERIS = 14,
    KATARI = 15,
    ORC = 16,
    RIBBET = 17,
    SIMIAH = 18,
};