export enum WeaponFeature {
    BARRIER = 1,
    // BONDED,
    // BOUNCING,
    // BRUTAL,
    // CONCUSSIVE,
    CUMBERSOME,
    // DEADLY,
    // DENSE,
    // DESTRUCTIVE,
    // DUELING,
    // ERUPTIVE,
    // GRAPPLING,
    // GREEDY,
    // HEALING,
    HEAVY,
    HOOK,
    // INVIGORATING,
    // LIFESTEALING,
    // LONG,
    // LUCKY,
    MASSIVE,
    // OTHERWORLDLY,
    // PAINFUL,
    PAIRED2,
    // PENETRATING,
    // PERSUASIVE,
    // POMPOUS,
    POWERFUL,
    PROTECTIVE,
    QUICK,
    RELIABLE,
    // RELOADING,
    // RETRACTABLE,
    // SERRATED,
    // SCARY,
    // SELF_CORRECTING,
    // SHARPWING,
    // TIMEBENDER,
    VERSATILE,
    WHIPCRACK,
}