import { AncestryAbility } from "../..";

export interface AncestryState {
    [AncestryAbility.PURPOSEFUL_DESIGN]? : {},
    [AncestryAbility.EFFICIENT]? : {},
    [AncestryAbility.SCALES]? : {},
    [AncestryAbility.ELEMENTAL_BREATH]? : {},
    [AncestryAbility.INCREASED_FORTITUDE]? : {},
    [AncestryAbility.THICK_SKIN]? : {},
    [AncestryAbility.QUICK_REACTIONS]? : {},
    [AncestryAbility.CELESTIAL_TRANCE]? : {},
    [AncestryAbility.WINGS]? : {},
    [AncestryAbility.LUCKBENDER]? : {},
    [AncestryAbility.LEAP]? : {},
    [AncestryAbility.KICK]? : {},
    [AncestryAbility.NATURAL_CALM]? : {},
    [AncestryAbility.CHARGE]? : {},
    [AncestryAbility.FUNGRIL_NETWORK]? : {},
    [AncestryAbility.DEATH_CONNECTION]? : {},
    [AncestryAbility.SHELL_OF_PROTECTION]? : {},
    [AncestryAbility.SLOW_AND_STEADY]? : {},
    [AncestryAbility.ENDURANCE]? : {},
    [AncestryAbility.REACH]? : {},
    [AncestryAbility.DANGER_SENSE]? : {},
    [AncestryAbility.SUREFOOTED]? : {},
    [AncestryAbility.YOUTHFUL_SPIRIT]? : {},
    [AncestryAbility.LITTLE_LUCKY]? : {},
    [AncestryAbility.HIGH_STAMINA]? : {},
    [AncestryAbility.ADAPTABILITY]? : {},
    [AncestryAbility.FEARLESS]? : {},
    [AncestryAbility.DREAD_VISAGE]? : {},
    [AncestryAbility.FELINE_INSTINCTS]? : {},
    [AncestryAbility.RETRACTING_CLAWS]? : {},
    [AncestryAbility.STURDY]? : {},
    [AncestryAbility.TUSKS]? : {},
    [AncestryAbility.LONG_TONGUE]? : {},
    [AncestryAbility.AMPHIBIOUS]? : {},
    [AncestryAbility.NIMBLE]? : {},
    [AncestryAbility.NATURAL_CLIMBER]? : {},
}